import type { CareerType } from "@lib/types";
import {
    siHtml5,
    siCss,
    siJavascript,
    siMysql,
    siCplusplus,
    siPhp,
    siDotnet,
    siKotlin,
    siSwift,
    siReact,
    siNextdotjs,
    siPostgresql,
    siTypescript,
    siTailwindcss
} from "simple-icons";

export const careerData: CareerType[] = [
    {
        category: "education",
        title: "Diploma in Information Technology",
        organization: "Tunku Abdul Rahman University College (TARC)",
        organizationUrl: "https://tarc.edu.my/",
        location: "Setapak, Kuala Lumpur, Malaysia",
        startDate: new Date(2020, 4),
        endDate: new Date(2022, 4),
        isCurrent: false,
        description: `Built a strong foundation in core software development concepts, mastering object-oriented programming and complex problem-solving with C++. Gained comprehensive exposure to the full software development lifecycle, from debugging to deployment, while designing systems involving web development, database management, and system architecture.`,
        learnedSkills: [
            { name: "HTML", icon: siHtml5.path },
            { name: "CSS", icon: siCss.path },
            { name: "JavaScript", icon: siJavascript.path },
            { name: "MySQL", icon: siMysql.path },
            { name: "C++", icon: siCplusplus.path },
        ],
    },
    {
        category: "internship",
        title: "Web Developer",
        organization: "Lakaran Cinta Sistem Empire",
        organizationUrl: "https://www.lakarancintasistem.com/",
        location: "Petaling Jaya, Shah Alam, Malaysia",
        startDate: new Date(2021, 9),
        endDate: new Date(2021, 11),
        isCurrent: false,
        description: `Engineered a responsive, customer-facing website for a local business utilizing HTML, CSS, and JavaScript. Focused on UI/UX best practices to improve site navigation and visual hierarchy, ensuring a seamless experience across mobile and desktop devices.`,
        learnedSkills: [
            { name: "HTML", icon: siHtml5.path },
            { name: "CSS", icon: siCss.path },
            { name: "JavaScript", icon: siJavascript.path },
        ],
    },
    {
        category: "education",
        title: "Bachelor of Information Technology (Honours) in Information Security",
        organization: "Tunku Abdul Rahman University of Management and Technology (TARUMT)",
        organizationUrl: "https://tarc.edu.my/",
        location: "Setapak, Kuala Lumpur, Malaysia",
        startDate: new Date(2022, 6),
        endDate: new Date(2024, 7),
        isCurrent: false,
        description: `Specialized in cybersecurity strategies to secure enterprise infrastructure. Mastered theoretical and practical applications of ethical hacking, cryptography, and penetration testing. Deepened knowledge in network security, risk assessment, and IT governance, preparing to tackle modern security threats in complex digital environments.`,
        learnedSkills: [
            { name: "PHP", icon: siPhp.path },
            { name: "ASP.NET", icon: siDotnet.path },
            { name: "Kotlin", icon: siKotlin.path },
        ],
    },
    {
        category: "internship",
        title: "Software Developer",
        organization: "Advanced Product Design Sdn. Bhd.",
        organizationUrl: "https://biocryptodisk.com/",
        location: "Skudai, Malaysia",
        startDate: new Date(2024, 1),
        endDate: new Date(2024, 7),
        isCurrent: false,
        description: `Contributed to the development of a secure video conferencing solution across web and desktop platforms. Engineered backend logic using PHP and enhanced native client performance for macOS and iOS using Swift. Collaborated within a cross-functional team to integrate secure data transmission features and optimize real-time communication.`,
        learnedSkills: [
            { name: "Swift", icon: siSwift.path },
        ],
    },
    {
        category: "job",
        title: "Web Developer",
        organization: "Morning Geek",
        organizationUrl: "https://www.morninggeek.com/",
        location: "Skudai, Malaysia",
        startDate: new Date(2024, 8),
        endDate: new Date(2026, 1),
        isCurrent: false,
        description: `Redesigned and rebuilt the CRM system for the Institution of Engineers, Singapore (IES), replacing their legacy platform with a modern solution using Next.js and Supabase. Developed core modules for membership management, professional programmes, and financial operations including invoices, receipts, and purchase orders. Responsible for fulfilling client requirements and handling daily service tickets and technical feedback to ensure smooth system performance.`,
        learnedSkills: [
            { name: "React", icon: siReact.path },
            { name: "Next.js", icon: siNextdotjs.path },
            { name: "TypeScript", icon: siTypescript.path },
            { name: "Tailwind CSS", icon: siTailwindcss.path },
            { name: "PostgreSQL", icon: siPostgresql.path },
        ],
    },
    {
        category: "job",
        title: "IT Officer",
        organization: "FOZ One",
        organizationUrl: "https://fozgroup.com/",
        location: "Senai, Malaysia",
        startDate: new Date(2026, 3),
        isCurrent: true,
        description: `Provided technical support and maintenance for IT systems within the organization. Collaborated with team members to ensure smooth operation of IT infrastructure and resolved technical issues in a timely manner.`
    }
];